name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to deploy to Github Packages'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Use Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@speciosa'
      - name: Install Dependencies
        run: npm ci
      - name: Set version
        run: npm version ${{ github.event.inputs.version }} --no-git-tag-version
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
