name: Release Package

on:
  release:
    types:
      - published

jobs:
  test:
    uses: ./.github/workflows/unit-test.yml
  get-version:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
      - name: Remove 'release/' from version
        id: get_version
        run: |
          value=${VERSION/release\//}
          echo "$value"
          echo "VERSION=$value" >> $GITHUB_OUTPUT
  call-publish:
    needs: get-version
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/publish.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      version: ${{ needs.get-version.outputs.version }}
